"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),api=require("./route-playback.js");
const floor=JSON.parse(fs.readFileSync("examples/routes/floor.json","utf8"));
const raw=JSON.parse(fs.readFileSync("examples/routes/timeline.json","utf8"));
const model=api.parse(raw,floor);
assert.equal(model.duration_s,20.7);
assert.equal(api.sample(model,0).state,"loading");
assert.deepEqual(api.sample(model,5.6).position,{x:4,y:5.3999999999999995});
assert.equal(api.sample(model,6.2).heading,0);
assert.equal(api.sample(model,17.7).state,"unloading");
assert.equal(api.sample(model,20.7).state,"delivered");
assert.deepEqual(api.sample(model,100).position,{x:13,y:8.5});
const mutate=fn=>{const copy=structuredClone(raw);fn(copy);assert.throws(()=>api.parse(copy,floor));};
mutate(t=>delete t.floor);
mutate(t=>t.floor.elements[0].x++);
mutate(t=>t.segments[0].end_s++);
mutate(t=>t.route.points[1].x++);
mutate(t=>t.route.distance_m++);
mutate(t=>t.speed_mps=0);
mutate(t=>t.duration_s=Infinity);
mutate(t=>t.route.clearance_m=2);
const changed=structuredClone(floor);changed.placementConstraintDraft=JSON.stringify({zones:[{x:4,y:5,w:1,d:1}]});
assert.throws(()=>api.parse(raw,changed));
const blocked=structuredClone(raw);blocked.floor=api.geometry(changed);
assert.throws(()=>api.parse(blocked,changed),/intersects/);
assert.deepEqual(api.parse(raw,floor),model);
console.log("Route playback: timing, geometry, stale floors, obstacles and boundaries pass");
