"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
global.window = global;
require("./view.js");
const source = fs.readFileSync(require.resolve("./app.js"), "utf8");
const names = ["rectsOverlap", "readConstraintDraft", "placementProblem", "inBounds", "overlapsAny", "nudgeSelected", "applySize", "rotateSelected", "findFreeSpotNear", "placeAt"];
const fields = { optConstraints:{value:'{"zones":[],"fixedIds":[]}'}, pW:{value:2}, pD:{value:1} };
const context = { GRID_W:20, GRID_H:20, CELL_M:0.5, state:{elements:[], selectedId:"a", flow:{playing:false}, idCounter:0}, ELEMENTS:{rack:{w:2,d:1,label:"Rack"}}, $:id=>fields[id], status:()=>{}, toast:()=>{}, scheduleSave:()=>{}, render:()=>{}, renderProps:()=>{}, selectElement:()=>{}, flowPause:()=>{context.state.flow.playing=false;} };
vm.createContext(context);
context.V = WT.view;
names.push("floorResizeProblem");
names.push("flowSignature");
names.push("validateImportIdentities");
for (const name of names) {
  const match = source.match(new RegExp("  function " + name + "\\([^]*?\\n  }"));
  assert.ok(match, name);
  vm.runInContext(match[0],context);
}
const setRules = rules => {fields.optConstraints.value=JSON.stringify(rules);};
const reset = () => {context.state.elements=[{id:"a",type:"rack",x:2,y:2,w:2,d:1}]; setRules({zones:[{x:2,y:1,w:1,d:2}],fixedIds:[]});};
reset();
assert.equal(context.placementProblem({x:2,y:2,w:2,d:1},"a"), "", "edge touching allowed with half-metre cells");
assert.match(context.placementProblem({x:3,y:2,w:2,d:1},"a"), /reserved area 1/);
const before=JSON.stringify(context.state.elements);
context.nudgeSelected(1,0);
assert.equal(JSON.stringify(context.state.elements),before);
fields.pW.value=3; context.applySize();
assert.equal(JSON.stringify(context.state.elements),before);
context.placeAt("rack",4,2);
assert.equal(context.state.elements.length,1);
const spot=context.findFreeSpotNear(context.state.elements[0]);
assert.ok(spot); assert.equal(context.placementProblem(spot,null),"");
setRules({fixedIds:["a"],zones:[]});
context.nudgeSelected(-1,0); context.rotateSelected(); context.applySize();
assert.equal(JSON.stringify(context.state.elements),before,"fixed object preserved across edits");
setRules({zones:[{x:1,y:1.5,w:1,d:1}]});
context.rotateSelected();
assert.equal(JSON.stringify(context.state.elements),before,"rotation into zone rejected");
setRules({zones:[{x:1,y:1,w:1,d:1}]});
context.state.flow.playing=true; context.nudgeSelected(-2,0);
assert.equal(context.state.elements[0].x,0,"existing conflict can move completely out");
assert.equal(context.state.flow.playing,false);
fields.optConstraints.value="{";
assert.match(context.placementProblem({x:8,y:8,w:2,d:1},null), /Correct placement/);
setRules({zones:[{x:0,y:0,w:11,d:1}]});
assert.match(context.placementProblem({x:8,y:8,w:2,d:1},null), /Correct placement/);
console.log("Manual placement: metre conversion, edge contact, reserved areas, fixed edits, recovery and malformed drafts pass.");
context.state.elements=[{id:"fixed-edge",x:18,y:2,w:2,d:1}];
setRules({fixedIds:["fixed-edge"],zones:[]});
const beforeResize=JSON.stringify(context.state.elements);
assert.match(context.floorResizeProblem(10,20),/fixed-edge/);
assert.equal(context.floorResizeProblem(20,20),"");
assert.equal(context.floorResizeProblem(30,30),"");
assert.equal(JSON.stringify(context.state.elements),beforeResize);
context.state.elements=[];
setRules({zones:[{x:9,y:0,w:1,d:1}]});
assert.match(context.floorResizeProblem(10,20),/Reserved area 1/);
assert.equal(context.floorResizeProblem(20,20),"");
fields.optConstraints.value="{";
assert.match(context.floorResizeProblem(30,30),/Correct placement/);
console.log("Floor resize: equipment preserved, reserved areas bounded, invalid drafts rejected, growth allowed.");
context.state.config={seed:42};
context.state.elements=[{id:"curve-a",type:"conveyor-curve",x:2,y:2,w:2,d:2,arc:"tr"}];
const originalSig=context.flowSignature();
context.state.elements[0].arc="br";
assert.notEqual(context.flowSignature(),originalSig,"square conveyor orientation invalidates playback");
context.state.elements[0].arc="tr";
assert.equal(context.flowSignature(),originalSig,"unchanged input is stable");
context.state.elements[0].id="curve-b";
assert.notEqual(context.flowSignature(),originalSig,"replacement identity invalidates playback");
console.log("Playback signature tracks square conveyor orientation and equipment identity.");
assert.throws(()=>context.validateImportIdentities([{id:"same"},{id:"same"}]),/Duplicate equipment ID/);
assert.throws(()=>context.validateImportIdentities([{id:"  "}]),/must not be empty/);
assert.doesNotThrow(()=>context.validateImportIdentities([{id:"a"},{id:"b"},{}]));
assert.ok(source.indexOf("validateImportIdentities(obj.elements)") < source.indexOf("WT.library.rebuildFrom(obj)"),"preflight before custom library mutation");
console.log("Import identity preflight rejects duplicates and empty IDs before mutation.");
