"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),api=require("./route-playback.js");
const floor=JSON.parse(fs.readFileSync("examples/routes/floor.json","utf8"));
const raw=JSON.parse(fs.readFileSync("examples/routes/timeline.json","utf8"));
const model=api.parse(raw,floor);
assert.equal(model.duration_s,20.7);
assert.equal(api.sample(model,0).state,"loading");
assert.deepEqual(api.sample(model,5.6).position,{x:4,y:5.3999999999999995});
assert.equal(api.sample(model,6.2).heading,0);
assert.equal(api.sample(model,17.7).state,"unloading");
assert.equal(api.sample(model,20.7).state,"delivered");
assert.deepEqual(api.sample(model,100).position,{x:13,y:8.5});
const mutate=fn=>{const copy=structuredClone(raw);fn(copy);assert.throws(()=>api.parse(copy,floor));};
mutate(t=>delete t.floor);
mutate(t=>t.floor.elements[0].x++);
mutate(t=>t.segments[0].end_s++);
mutate(t=>t.route.points[1].x++);
mutate(t=>t.route.distance_m++);
mutate(t=>t.speed_mps=0);
mutate(t=>t.duration_s=Infinity);
mutate(t=>t.route.clearance_m=2);
const changed=structuredClone(floor);changed.placementConstraintDraft=JSON.stringify({zones:[{x:4,y:5,w:1,d:1}]});
assert.throws(()=>api.parse(raw,changed));
const blocked=structuredClone(raw);blocked.floor=api.geometry(changed);
assert.throws(()=>api.parse(blocked,changed),/intersects/);
assert.deepEqual(api.parse(raw,floor),model);
const bound=structuredClone(raw),manifest={id:"P",pick_id:"K",source_id:"A",destination_id:"B",order_id:"O",line_id:"L",item_id:"I",quantity:4,unit:"piece",version:2,updated_at:"2026-09-19T10:00:00.000000+00:00"};
bound.package_snapshot={...manifest};bound.location_access={A:"PICK-ACCESS",B:"PACK-ACCESS"};
assert.equal(api.parse(bound,floor,manifest).package_snapshot.id,"P");
assert.throws(()=>api.parse(bound,floor));
for(const field of Object.keys(manifest))assert.throws(()=>api.parse(bound,floor,{...manifest,[field]:"changed"}));
bound.location_access.B="AISLE-B";assert.throws(()=>api.parse(bound,floor,manifest),/access nodes/);
assert.deepEqual(api.project({x:4,y:6},"plan"),{x:4,y:6});
assert.deepEqual(api.project({x:4,y:6},"iso"),{x:-Math.sqrt(3),y:5});
for(const view of ["plan","iso"]){
  const position=api.sample(model,10).position,camera=api.camera(model.floor,view,4,position),p=api.project(position,view);
  assert.ok(Math.abs(camera.x+camera.width/2-p.x)<1e-12);
  assert.ok(Math.abs(camera.y+camera.height/2-p.y)<1e-12);
  const fit=api.camera(model.floor,view,1,position);
  for(const corner of [{x:0,y:0},{x:20,y:0},{x:20,y:12},{x:0,y:12}]){
    const q=api.project(corner,view);assert.ok(q.x>fit.x&&q.y>fit.y&&q.x<fit.x+fit.width&&q.y<fit.y+fit.height);
  }
}
assert.throws(()=>api.project({x:Infinity,y:0},"iso"));
assert.throws(()=>api.camera(model.floor,"plan",3,{x:0,y:0}));
const reserved=JSON.parse(fs.readFileSync("examples/routes/reserved-timeline.json","utf8"));
const queued=api.parse(reserved,floor);
assert.equal(queued.playback_duration_s,40);
assert.equal(api.sample(queued,0).state,"not-released");
assert.equal(api.sample(queued,10).state,"queued");
assert.deepEqual(api.sample(queued,10).position,{x:4,y:4.8});
assert.match(api.sample(queued,10).wait,/TRANSFER-A/);
assert.equal(api.sample(queued,20.7).state,"loading");
assert.equal(api.sample(queued,30).state,"travelling");
assert.equal(api.sample(queued,40).state,"unloading");
assert.equal(api.sample(queued,100).state,"unloading");
const overlap=structuredClone(reserved);overlap.reservation.schedule.requests[1].planned_start_s=1;overlap.reservation.schedule.requests[1].planned_end_s=21.7;
assert.throws(()=>api.parse(overlap,floor),/capacity exceeded/);
const mismatch=structuredClone(reserved);mismatch.reservation.request_id="missing";
assert.throws(()=>api.parse(mismatch,floor),/does not match/);
console.log("Route playback: timing, geometry, stale floors, obstacles and boundaries pass");
