"""Write run-ledger-sql.js from tools/run_ledger.py - the SQL the viewer shows under every table.

    python tools/export_viewer_sql.py            # rewrites run-ledger-sql.js
    python tools/export_viewer_sql.py --check    # exit 1 when the committed file is stale

Each entry is the statement SQLite runs for that view, byte for byte, minus the
`CREATE VIEW IF NOT EXISTS <name> AS` prefix; the group lists name which views the
tool prints as planner / invariant / detail / compare views. test/test_run_ledger.py
regenerates the text in memory and fails when the committed file differs, and proves
that every text runs in SQLite exactly as shown.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import run_ledger as RL

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "run-ledger-sql.js"
PREFIX = re.compile(r"\A\s*CREATE VIEW IF NOT EXISTS (\w+) AS\s*")
GROUPS = ("PLANNER_VIEWS", "INVARIANT_VIEWS", "DETAIL_VIEWS", "COMPARE_VIEWS", "REPLICATION_VIEWS")


def view_bodies() -> dict[str, str]:
    """name -> the view's SELECT / WITH text exactly as it sits in run_ledger.VIEWS."""
    out: dict[str, str] = {}
    for name, ddl in RL.VIEWS.items():
        m = PREFIX.match(ddl)
        if not m or m.group(1) != name:
            raise ValueError(f"{name}: the DDL does not start with its own CREATE VIEW prefix")
        body = ddl[m.end():]
        if body.split(None, 1)[0].upper() not in ("SELECT", "WITH"):
            raise ValueError(f"{name}: the view body must start with SELECT or WITH")
        if "..." in body:
            raise ValueError(f"{name}: the view body is abbreviated")
        out[name] = body
    return out


def render() -> str:
    bodies = view_bodies()
    entries = ",\n".join(f"  {json.dumps(name)}: {json.dumps(body)}" for name, body in bodies.items())
    meta: dict[str, object] = {"generated_from": "tools/run_ledger.py", "views": len(bodies)}
    for group in GROUPS:
        if hasattr(RL, group):
            meta[group[: -len("_VIEWS")].lower()] = list(getattr(RL, group))
    return (
        "/* GENERATED by tools/export_viewer_sql.py from tools/run_ledger.py (VIEWS) - do not edit.\n"
        " * Each text is the statement SQLite runs for that view, byte for byte, minus the\n"
        " * `CREATE VIEW IF NOT EXISTS <name> AS` prefix. test/test_run_ledger.py fails when stale. */\n"
        "window.RunLedgerSQL = {\n" + entries + "\n};\n"
        "window.RunLedgerSQLMeta = " + json.dumps(meta, indent=2) + ";\n"
    )


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 when run-ledger-sql.js is stale")
    a = ap.parse_args(argv)
    text = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None
    if a.check:
        fresh = current == text
        print("run-ledger-sql.js is " + ("fresh" if fresh else "STALE - run python tools/export_viewer_sql.py"))
        return 0 if fresh else 1
    with TARGET.open("w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {TARGET.name}: {len(RL.VIEWS)} views")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
