/* tools/route_graph.mjs - v3.68: render the declared route graphs as a documentation page.
 *
 *   node tools/route_graph.mjs                    print the graphs to stdout
 *   node tools/route_graph.mjs --out docs/ROUTE_GRAPH.md
 *   node tools/route_graph.mjs --check            fail if docs/ROUTE_GRAPH.md is stale
 *   node tools/route_graph.mjs --json out.json    the graphs as data
 *
 * The page is GENERATED, never hand-edited: the graphs come from routing.js itself,
 * so a change to an archetype shows up here or the --check fails. The diagrams are
 * mermaid, which renders in GitHub and in the artifact viewer without a library.
 *
 * Honesty, carried onto the page: these are declared teaching recipes informed by
 * ordinary distribution-centre practice, not a measurement of any plant, and a node
 * is a process step - never a person.
 */
import fs from "node:fs";
import path from "node:path";
import { loadWT, root } from "./ledger_env.mjs";

loadWT(["domain.js", "iso.js", "shapes.js", "routing.js"]);
const R = globalThis.WT.routing;

const ARROW = { then: "-->", outcome: "-.->", check: "==>", rework: "==>", "write-off": "-.->" };
const EDGE_LABEL = { then: "", outcome: "outcome", check: "check", rework: "REWORK", "write-off": "write-off" };

function mermaid(g) {
  const lines = ["flowchart LR"];
  for (const n of g.nodes) {
    const shape = n.maxVisits > 1 ? ["([", "])"] : ["[", "]"];
    lines.push("  " + safe(n.id) + shape[0] + '"' + n.label.replace(/"/g, "'") + (n.maxVisits > 1 ? " (up to " + n.maxVisits + " visits)" : "") + '"' + shape[1]);
  }
  for (const e of g.edges) {
    const label = e.kind === "outcome" ? e.outcome : EDGE_LABEL[e.kind];
    lines.push("  " + safe(e.from) + " " + (ARROW[e.kind] || "-->") + (label ? "|" + label + "|" : "") + " " + safe(e.to));
  }
  return lines.join("\n");
}
const safe = (id) => id.replace(/[^A-Za-z0-9_]/g, "_");

function walkLine(g, opts) {
  return R.walk(g, opts).join(" → ");
}

function page() {
  const out = [];
  out.push("# The route graph (v3.68)");
  out.push("");
  out.push("*Generated by `node tools/route_graph.mjs --out docs/ROUTE_GRAPH.md`. Do not edit by hand: the graphs are read out of `routing.js`, and `--check` fails if this page has drifted from the code.*");
  out.push("");
  out.push("Until v3.68 a route was a **list** of operations. Four of the limits this app documents about itself ended with the same sentence - *cycles need a graph* - because a list cannot say \"do that step again\". A rework had to be written out flat: the operation, its check, the operation once more. A unit that erred twice could not be expressed at all.");
  out.push("");
  out.push("A route is now a directed graph, and the list is what you get by **walking** it. Nothing a caller sees changed when this landed: every route, every run id and every committed fixture is byte for byte what it was, and `verify_routegraph.js` pins each list against the one v3.67 produced. What changed is what the model can say.");
  out.push("");
  out.push("## The edge kinds");
  out.push("");
  out.push("| Kind | Drawn | Meaning |");
  out.push("|---|---|---|");
  for (const k of Object.keys(R.EDGE_KINDS)) out.push("| `" + k + "` | " + (k === "rework" ? "thick, labelled REWORK" : k === "check" ? "thick" : k === "then" ? "plain" : "dotted") + " | " + R.EDGE_KINDS[k] + " |");
  out.push("");
  out.push("A node drawn with rounded ends is one a unit may visit **more than once**. That is the cycle, and it is bounded: `maxVisits` is 2 in this release, which is one redo - exactly the detour the flat list used to spell out.");
  out.push("");
  out.push("## The eight order types");
  out.push("");
  for (const a of R.ARCHETYPES) {
    const g = R.graphOf(a.id);
    out.push("### " + a.label);
    out.push("");
    out.push(a.desc.replace(/\s+/g, " ").trim());
    out.push("");
    out.push("```mermaid");
    out.push(mermaid(g));
    out.push("```");
    out.push("");
    if (g.outcomes) {
      out.push("Walks:");
      out.push("");
      for (const oc of g.outcomes) out.push("- **" + oc.label + "** (declared share " + oc.share + "): " + walkLine(g, { outcome: oc.id }));
      out.push("");
    } else {
      out.push("Walk: " + walkLine(g, {}));
      out.push("");
    }
  }
  out.push("## An error branch, which is where the loop is");
  out.push("");
  out.push("The error what-if of v3.54 adds edges rather than a second recipe. A mis-pick at the each-pick face puts a **check** edge into the verification step and a **rework** edge straight back to the pick:");
  out.push("");
  const ge = R.graphOf("piece-pick", { error: { kind: "mis-pick", op: "piece-pick" } });
  out.push("```mermaid");
  out.push(mermaid(ge));
  out.push("```");
  out.push("");
  out.push("- Without the error realised, the walk is: " + walkLine(ge, {}));
  out.push("- With it: **" + walkLine(ge, { error: { kind: "mis-pick", op: "piece-pick" } }) + "**");
  out.push("");
  out.push("Handling damage is the other shape: a terminal **write-off** edge that takes the unit off the route at the bench.");
  out.push("");
  const gd = R.graphOf("case-pick", { error: { kind: "damage", op: "palletise" } });
  out.push("```mermaid");
  out.push(mermaid(gd));
  out.push("```");
  out.push("");
  out.push("Walk with the damage realised: **" + walkLine(gd, { error: { kind: "damage", op: "palletise" } }) + "**");
  out.push("");
  out.push("## What is still a limit");
  out.push("");
  out.push("The refactor did not quietly close anything it did not close.");
  out.push("");
  out.push("- **A unit that errs twice is still not modelled**, and the graph now says precisely why - which the flat list could not. Raising a node's `maxVisits` from 2 to 3 changes nothing on its own: the **check** edge is entered only on the *first* visit to a step, so a unit that has been reworked once is never offered a second verification. A second error is a second draw from the quota dispatcher, not a second lap of the loop. The visit bound is a guard rail, not the model.");
  out.push("- **Quality control is still a pass-through node** with one ordinary edge out. The graph can hold the branch to blocked stock, where a unit dwells until it is released. Nothing declares it yet.");
  out.push("- **Replenishment is still a node in the each-pick chain**, not the order-independent loop it is in a real building. The same is true of re-slotting.");
  out.push("- **The order of the recipe is still fixed.** VDI 3590 says the sequence is not necessarily determined and that steps may be omitted; the graph can express an optional step or an alternative path, and no archetype declares one yet.");
  out.push("- **The walk takes no random draw.** Which branch a unit takes is decided by the quota dispatcher, exactly as before.");
  out.push("");
  out.push("## Honesty");
  out.push("");
  out.push("> " + R.GRAPH_HONESTY);
  out.push("");
  out.push("## Reproduce");
  out.push("");
  out.push("```sh");
  out.push("node tools/route_graph.mjs --check");
  out.push("node verify_routegraph.js");
  out.push("```");
  return out.join("\n") + "\n";
}

const argv = process.argv.slice(2);
const arg = (name) => { const i = argv.indexOf(name); return i >= 0 ? argv[i + 1] : null; };
const text = page();

if (argv.includes("--json")) {
  const file = arg("--json") || "route-graphs.json";
  const data = { schema: R.GRAPH_SCHEMA, honesty: R.GRAPH_HONESTY, edge_kinds: R.EDGE_KINDS, graphs: R.ARCHETYPES.map((a) => R.graphOf(a.id)) };
  fs.writeFileSync(path.join(root, file), JSON.stringify(data, null, 2) + "\n");
  console.log("wrote " + file + " (" + data.graphs.length + " graphs)");
} else if (argv.includes("--check")) {
  const file = path.join(root, "docs", "ROUTE_GRAPH.md");
  const have = fs.existsSync(file) ? fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n") : "";
  if (have !== text) { console.error("STALE: docs/ROUTE_GRAPH.md does not match routing.js. Run: node tools/route_graph.mjs --out docs/ROUTE_GRAPH.md"); process.exit(1); }
  console.log("docs/ROUTE_GRAPH.md is fresh (" + R.ARCHETYPES.length + " graphs)");
} else if (argv.includes("--out")) {
  const file = arg("--out") || path.join("docs", "ROUTE_GRAPH.md");
  fs.writeFileSync(path.join(root, file), text);
  console.log("wrote " + file + " (" + text.split("\n").length + " lines, " + R.ARCHETYPES.length + " graphs)");
} else {
  process.stdout.write(text);
}
