/* tools/units_page.mjs - v3.70: render the rate-and-speed registry as a documentation page.
 *
 *   node tools/units_page.mjs                     print to stdout
 *   node tools/units_page.mjs --out docs/UNITS_AND_RATES.md
 *   node tools/units_page.mjs --check             fail if docs/UNITS_AND_RATES.md is stale
 *
 * The page is GENERATED from units.js, never hand-edited, so a rate that changes in
 * the code either shows up here or the --check fails. It exists mainly to carry the
 * findings the registry surfaced: two models that disagree about how long a tick is,
 * two travel speeds that differ by a factor of about 206, a conveyor with no speed,
 * a declared speed nothing reads, and a coefficient of variation with two values.
 */
import fs from "node:fs";
import path from "node:path";
import { loadWT, root } from "./ledger_env.mjs";

loadWT(["domain.js", "iso.js", "shapes.js", "units.js"]);
const U = globalThis.WT.units;

const num = (v) => (Number.isInteger(v) ? String(v) : String(v));

function page() {
  const L = [];
  L.push("# Units, rates and speeds (v3.70)");
  L.push("");
  L.push("*Generated by `node tools/units_page.mjs --out docs/UNITS_AND_RATES.md`. Do not edit by hand: the table is read out of `units.js`, and `--check` fails if this page has drifted from the code.*");
  L.push("");
  L.push("Until v3.70 every rate and speed in this app was a bare number in a parameter block, and the conversion between ticks, hours, seconds and metres was written out by hand wherever it was needed. Three models each did it their own way. This page is the first place all of them are listed together, and listing them together is what made five disagreements visible.");
  L.push("");
  L.push("**This release changes no behaviour.** Every value below is a copy of a literal that is still where it was, so every run, run id, fixture and pinned digest is exactly what it was. Adopting the conversions at the call sites is a later, separately gated step, one site at a time.");
  L.push("");
  L.push("## What listing them together showed");
  L.push("");
  for (const f of U.FINDINGS) {
    L.push("### " + f.what);
    L.push("");
    L.push(f.detail);
    L.push("");
    L.push("Entries: " + f.ids.map((id) => "`" + id + "`").join(", "));
    L.push("");
  }
  L.push("## The registry");
  L.push("");
  L.push("A value is **cited**, a **teaching** value, or **measured** on a named source with its n. Nothing is unlabelled. A teaching value is a number chosen so the model is instructive; it is not a measurement of any plant.");
  L.push("");
  for (const owner of U.owners()) {
    L.push("### " + owner);
    L.push("");
    L.push("| Entry | Value | Unit | Kind | What it is |");
    L.push("|---|---|---|---|---|");
    for (const e of U.list(owner)) {
      L.push("| `" + e.id + "` | " + num(e.value) + " | " + e.unit + " | " + e.kind + " | " + e.label + " |");
    }
    L.push("");
    const noted = U.list(owner).filter((e) => e.note);
    if (noted.length) {
      for (const e of noted) L.push("- **`" + e.id + "`** — " + e.note);
      L.push("");
    }
  }
  L.push("## The conversions");
  L.push("");
  L.push("Each one is written in the **same order** as the expression it stands for, because floating-point arithmetic is not associative: `cap * (1/tph)` is not `cap / tph`. A caller adopts one only where equality has been proven on real values.");
  L.push("");
  L.push("| Conversion | Reads | Worked value |");
  L.push("|---|---|---|");
  L.push("| `perTick(unitsPerHr, ticksPerHour)` | units per hour to units per tick | 65.8 at 60 gives " + U.perTick(65.8, 60) + " |");
  L.push("| `ticksPerUnit(unitsPerTick)` | a rate to the ticks one unit costs | 0.02 gives " + U.ticksPerUnit(0.02) + " |");
  L.push("| `secondsPerUnit(unitsPerHr)` | units per hour to seconds per unit | 45 gives " + U.secondsPerUnit(45) + " |");
  L.push("| `unitsPerHrFromSeconds(sec)` | a cycle time to units per hour | 30 gives " + U.unitsPerHrFromSeconds(30) + " |");
  L.push("| `minutesPerTick(ticksPerHour)` | how long a tick is | 60 gives " + U.minutesPerTick(60) + ", 4 gives " + U.minutesPerTick(4) + " |");
  L.push("| `takt(shiftSec, demandPerShift)` | the takt time of a line | 28800 over 480 gives " + U.takt(28800, 480) + " s |");
  L.push("| `to(quantity, unit)` | any conversion inside one dimension, refused across two | 0.35 cells/tick is " + U.to(U.quantity(0.35, "cells/tick"), "m/s") + " m/s |");
  L.push("");
  L.push("A conversion across dimensions is **refused by name** rather than silently scaled: asking for a rate in metres per second raises *refusing to convert units/hr (rate) to m/s (speed)*.");
  L.push("");
  L.push("## What is deliberately not adopted");
  L.push("");
  L.push("Two sites keep their literal and will keep it, and the reason is floating point rather than taste.");
  L.push("");
  for (const n of U.NOT_ADOPTED) {
    L.push("- **" + n.site + "** — " + n.reason);
  }
  L.push("");
  L.push("## What the source scan reports, and what it cannot see");
  L.push("");
  L.push("`unregistered(source)` scans a module's text for rate-shaped declarations and reports the ones the registry does not carry. It reads **names**, so a rate called something unexpected can hide from it. On its first run it found one real omission — a manufacturing source's emit rate that had been missed by hand — and two things that are correctly not entries:");
  L.push("");
  for (const e of U.SCAN_EXPLAINED) L.push("- **`" + e.name + "`** in " + e.owner + " — " + e.reason);
  L.push("");
  L.push("## Honesty");
  L.push("");
  L.push("> " + U.HONESTY);
  L.push("");
  L.push("## Reproduce");
  L.push("");
  L.push("```sh");
  L.push("node tools/units_page.mjs --check");
  L.push("node verify_units.js");
  L.push("```");
  return L.join("\n") + "\n";
}

const argv = process.argv.slice(2);
const arg = (n) => { const i = argv.indexOf(n); return i >= 0 ? argv[i + 1] : null; };
const text = page();

if (argv.includes("--check")) {
  const file = path.join(root, "docs", "UNITS_AND_RATES.md");
  const have = fs.existsSync(file) ? fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n") : "";
  if (have !== text) { console.error("STALE: docs/UNITS_AND_RATES.md does not match units.js. Run: node tools/units_page.mjs --out docs/UNITS_AND_RATES.md"); process.exit(1); }
  console.log("docs/UNITS_AND_RATES.md is fresh (" + U.ids().length + " entries, " + U.FINDINGS.length + " findings)");
} else if (argv.includes("--out")) {
  const file = arg("--out") || path.join("docs", "UNITS_AND_RATES.md");
  fs.writeFileSync(path.join(root, file), text);
  console.log("wrote " + file + " (" + text.split("\n").length + " lines, " + U.ids().length + " entries)");
} else {
  process.stdout.write(text);
}
